trigger:
  branches:
    include:
      - "*"
  tags:
    include:
      - "v*"

pr:
  - "*"

jobs:
  - job: build_and_test_base
    displayName: "macOS-10.14"
    timeoutInMinutes: 0
    pool:
      vmImage: 'macOS-10.14'
    steps:
      - checkout: self
        displayName: "Checkout repository"
        fetchDepth: 64
      - bash: |
          sudo mkdir /opt/local.old
          sudo mv /usr/local/* /opt/local.old
        displayName: "Cleanup /usr/local"
      - bash: |
          set -eu
          ./configure
        displayName: "Configure MacPorts Base"
      - bash: |
          set -eu
          make -j$(sysctl -n hw.activecpu)
        displayName: "Build MacPorts Base"
      - bash: |
          set -eu
          sudo make install
        displayName: "Install MacPorts Base"
      - bash: |
          set -eu
          make test
        displayName: "Test MacPorts Base"
